#!/bin/bash
#
pyinstaller --windowed \
            --noconfirm \
            --icon="build_tools/coffeegrindsize.icns" \
            --name "coffeegrindsize" \
            --hidden-import cmath \
            coffeegrindsize.py
build_tools/fix_info_plist.py $(poetry version --short) ./dist/coffeegrindsize.app/Contents/Info.plist
